name: My First Action
on:
  - push

jobs:
  my-first-job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: cat /etc/os-release
      - name: CPU
        run: cat /proc/cpuinfo
      - name: Ram
        run: free -m
      - name: ls pwd
        run: |
          ls -a
          pwd
          whoami